### ISSUE TITLE
Umbraco.CheckBoxList values are not transferred when used in Doc Type Grid Editor

### ISSUE THREAD

**Issue by hemraker** [umbraco/Umbraco.Deploy.Contrib#11]
**What did you do?**
Set up two doc types

- Home Page
  - bodyText (Umbraco.Grid)
- Details
  - detailsChoice (Umbraco.CheckBoxList)
  - detailsSelection (Umbraco.RadioButtonList)
  - detailsDescription (Umbraco.TinyMCEv3)

Created a content item where the Details document type is selected using **Doc Type Grid Editor**. Polpulated all three properties and transferred the content to target environment.

**What did you expect to happen**
The content item to be transferred to target environment with all three properties populated.

**What actually happened**
Content item was transferred but only two of the properties were populated in the target environment. The value for the checkboxlist did not get transferred (see image).
Radio button list and rte transferred as expected, so seems specific to the checkbox list.

![checkboxlist](https://user-images.githubusercontent.com/3663619/30520448-278c7bfc-9bae-11e7-8f57-3206069d3270.jpg)

**Comment by clausjensen** [comment]
http://issues.umbraco.org/issue/deploy-397
