### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco.Deploy.Contrib#4]
As the issue tracker was closed down on the examples repo, I'm just reposting your questions here @hfloyd

> Should "deploy" related issues be added to the "Courier" area (http://issues.umbraco.org/issues/COU), or to the Umbraco Cloud one (http://issues.umbraco.org/issues/UAAS) or will there be a new "Deploy" area added to the Issues site?

We actually have a tracker specifically for the Deploy code base - it is however internal for now and need a little bit of cleaning and aligning before we open it up to public access. So for now, post issues to http://issues.umbraco.org/issues/UAAS for Deploy (as Deploy is Cloud only as of currently) and http://issues.umbraco.org/issues/COU for Courier 😃

> Regarding this specific bug... For myself, and possibly for others (such as the OP @rlynggaard), this causes a serious "breaking change" in existing sites which have been upgraded to 7.6 + Deploy. Is it possible to create a "fixed" copy of this ValueConnector - either via a PR to Deploy, or by just dropping a new ValueConnector into a site? If the latter, is there some way to "override" the original version which is included with Deploy?

PR's are very welcome and I'll get the fixes pulled in ASAP. It can however be a bit hard currently if it's for one of the internal connectors (not in the contrib repo) as we can't really open up the main repo to public.

I will look into what the options are for overriding the existing connectors (I can't remember exactly how/if this will work off the top of my head) ... which I guess would allow you to actually have an overriding copy of the core connectors and debug and fix them in a separate assembly - and then we can cherry-pick the fixes from there.

**Comment by hfloyd** [comment]
Thanks, @clausjensen 

So, regarding what Umbraco Deploy views as "Standard" versus "Custom" Property Editors, it seems there is a bit of overlap now, when comparing your examples and these in the "Contrib" repo...

Umbraco.Deploy.Contrib | Umbraco.Deploy.ValueConnectors | Duplicate?
---------------------- | ------------------------------- | ------------------
ValueConnectors/ArchetypeValueConnector.cs | ArchetypeValueConnector.cs | Y
GridCellValueConnectors/DocTypeGridEditorCellValueConnector.cs | GridValueConnector.cs | ?
GridCellValueConnectors/LeBlenderGridCellValueConnector.cs | GridValueConnector.cs | ?
ValueConnectors/MultiUrlPickerValueConnector.cs | MultiUrlPickerValueConnector.cs | Y
ValueConnectors/NestedContentValueConnector.cs | NestedContentConnector.cs | Y

Should these be in both locations? 

As per my previous issue (https://github.com/umbraco/Umbraco.Deploy.Contrib/issues/3) it appears that the LeBlender one at least is conflicting when it is compiled into this "Contrib" repo...

**Comment by hfloyd** [comment]
So, I was able to fix the original issue with single links in the MultiUrlPicker here, and it seems to override the one in the Umbraco.Deploy.ValueConnectors namespace automatically. See PR #5

**Comment by clausjensen** [comment]
There's no overlap, as the ones in the contrib repository are removed from the newest version of Deploy to avoid conflicts.

Sounds good that it just overrides the internal one - that's the way it should work, I just haven't confirmed it recently. I'll get your PR pulled in 😃
